source 'https://rubygems.org'
gem 'rails', '4.2.1'
gem 'sqlite3'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'hurley'

group :development, :test do
  gem 'pry'
  gem 'binding_of_caller' # allows interactive web console when using better_errors; think web-based pry
  gem 'better_errors'
  gem 'spring'
end

group :test do
  gem 'webmock'
  gem 'vcr'

end
